// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// Delta3DWeightsC
arma::cube Delta3DWeightsC(Rcpp::NumericVector vx, Rcpp::NumericVector Datasample);
RcppExport SEXP _GeneralizedUmatrix_Delta3DWeightsC(SEXP vxSEXP, SEXP DatasampleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type vx(vxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Datasample(DatasampleSEXP);
    rcpp_result_gen = Rcpp::wrap(Delta3DWeightsC(vx, Datasample));
    return rcpp_result_gen;
END_RCPP
}
// addRowWiseC
NumericMatrix addRowWiseC(NumericMatrix WeightVectors, NumericVector DataPoint);
RcppExport SEXP _GeneralizedUmatrix_addRowWiseC(SEXP WeightVectorsSEXP, SEXP DataPointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type WeightVectors(WeightVectorsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DataPoint(DataPointSEXP);
    rcpp_result_gen = Rcpp::wrap(addRowWiseC(WeightVectors, DataPoint));
    return rcpp_result_gen;
END_RCPP
}
// trainstepC
arma::cube trainstepC(Rcpp::NumericVector vx, Rcpp::NumericVector vy, Rcpp::NumericMatrix DataSampled, Rcpp::NumericMatrix BMUsampled, double Lines, double Columns, double Radius, bool toroid, int NoCases);
RcppExport SEXP _GeneralizedUmatrix_trainstepC(SEXP vxSEXP, SEXP vySEXP, SEXP DataSampledSEXP, SEXP BMUsampledSEXP, SEXP LinesSEXP, SEXP ColumnsSEXP, SEXP RadiusSEXP, SEXP toroidSEXP, SEXP NoCasesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type vx(vxSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type vy(vySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type DataSampled(DataSampledSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type BMUsampled(BMUsampledSEXP);
    Rcpp::traits::input_parameter< double >::type Lines(LinesSEXP);
    Rcpp::traits::input_parameter< double >::type Columns(ColumnsSEXP);
    Rcpp::traits::input_parameter< double >::type Radius(RadiusSEXP);
    Rcpp::traits::input_parameter< bool >::type toroid(toroidSEXP);
    Rcpp::traits::input_parameter< int >::type NoCases(NoCasesSEXP);
    rcpp_result_gen = Rcpp::wrap(trainstepC(vx, vy, DataSampled, BMUsampled, Lines, Columns, Radius, toroid, NoCases));
    return rcpp_result_gen;
END_RCPP
}
// trainstepC2
NumericVector trainstepC2(NumericVector esomwts, NumericVector aux, NumericMatrix DataSampled, NumericMatrix BMUsampled, double Lines, double Columns, double Weights, double Radius, bool toroid, int NoCases);
RcppExport SEXP _GeneralizedUmatrix_trainstepC2(SEXP esomwtsSEXP, SEXP auxSEXP, SEXP DataSampledSEXP, SEXP BMUsampledSEXP, SEXP LinesSEXP, SEXP ColumnsSEXP, SEXP WeightsSEXP, SEXP RadiusSEXP, SEXP toroidSEXP, SEXP NoCasesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type esomwts(esomwtsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type aux(auxSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type DataSampled(DataSampledSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type BMUsampled(BMUsampledSEXP);
    Rcpp::traits::input_parameter< double >::type Lines(LinesSEXP);
    Rcpp::traits::input_parameter< double >::type Columns(ColumnsSEXP);
    Rcpp::traits::input_parameter< double >::type Weights(WeightsSEXP);
    Rcpp::traits::input_parameter< double >::type Radius(RadiusSEXP);
    Rcpp::traits::input_parameter< bool >::type toroid(toroidSEXP);
    Rcpp::traits::input_parameter< int >::type NoCases(NoCasesSEXP);
    rcpp_result_gen = Rcpp::wrap(trainstepC2(esomwts, aux, DataSampled, BMUsampled, Lines, Columns, Weights, Radius, toroid, NoCases));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_GeneralizedUmatrix_Delta3DWeightsC", (DL_FUNC) &_GeneralizedUmatrix_Delta3DWeightsC, 2},
    {"_GeneralizedUmatrix_addRowWiseC", (DL_FUNC) &_GeneralizedUmatrix_addRowWiseC, 2},
    {"_GeneralizedUmatrix_trainstepC", (DL_FUNC) &_GeneralizedUmatrix_trainstepC, 9},
    {"_GeneralizedUmatrix_trainstepC2", (DL_FUNC) &_GeneralizedUmatrix_trainstepC2, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_GeneralizedUmatrix(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
